create:
  build:
    context: ./
      #Api  Service
      #Use the DockerFile in that Directory
    dockerfile: Dockerfile
  ports:
    - "5001:80"
  restart: always
  #Specify Environment Variables for the Api Service
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
